// <auto-generated />
namespace DoAnWebTruyenTranh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TruyenTranh1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TruyenTranh1));
        
        string IMigrationMetadata.Id
        {
            get { return "202303300738007_TruyenTranh1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
